/*
Challenges
-----------------------------
Link:https://www.hackerrank.com/contests/wissen-coding-challenge-2021/challenges/challenges
-----------------------------

*/
Solution

SELECT H.HACKER_ID,H.NAME,COUNT(C.CHALLENGE_ID)
FROM HACKERS H, CHALLENGES C
WHERE H.HACKER_ID=C.HACKER_ID
GROUP BY H.HACKER_ID,H.NAME
HAVING COUNT(C.CHALLENGE_ID) NOT IN
   (SELECT COUNT(CHALLENGE_ID) 
   FROM CHALLENGES WHERE HACKER_ID<>H.HACKER_ID 
   GROUP BY HACKER_ID 
   HAVING COUNT(CHALLENGE_ID)<>
	     (SELECT MAX(COUNT(CHALLENGE_ID)) 
			 FROM CHALLENGES 
       GROUP BY HACKER_ID))
ORDER BY COUNT(C.CHALLENGE_ID) DESC,HACKER_ID;